### ISSUE TITLE
happy birthday

### ISSUE THREAD

**Issue by yuvlian** [GlitzyIsBored/GlitzyIsBored.github.io#1]
![image](https://github.com/user-attachments/assets/f78730df-de65-440f-a6a1-f045970c4fbe)

**Comment by GlitzyIsBored** [comment]
> ![image](https://private-user-images.githubusercontent.com/138542238/351772373-f78730df-de65-440f-a6a1-f045970c4fbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NTkwODEsIm5iZiI6MTcyMTg1ODc4MSwicGF0aCI6Ii8xMzg1NDIyMzgvMzUxNzcyMzczLWY3ODczMGRmLWRlNjUtNDQwZi1hNmExLWYwNDU5NzBjNGZiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQyMjA2MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTFiNjk2ZWE3ZTNhMDZkODI4NDNhNjlmNTFhMzQzMTdlMzc1YTE4ODI1OTg1NDJlN2QwNTNjNTNhNDAwNmMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gk_TEvyhpZwsXk0SzqLgwFb3cpTZ8xkohui-jmGomlQ)

OMG THANK YOU SO. UCH YULIAN!!❤️

**Comment by GlitzyIsBored** [comment]
Real my bday should’ve been on May
